##广播机制与向量化距离计算

In [3]:
import numpy as np

points_A = np.random.randint(0, 101, (5, 2))
points_B = np.random.randint(0, 101, (8, 2))

# 2. 距离矩阵计算 
diff = points_A[:, None, :] - points_B[None, :, :]
distance_matrix = np.sqrt(np.sum(diff**2, axis=2))

# 3. 轴向数据聚合
min_distances = np.min(distance_matrix, axis=1)

# 4. 复合条件查询
mask = np.any(distance_matrix < 20, axis=0)
indices = np.where(mask)[0]

# 打印结果供参考
print( points_A)
print( points_B)
print( distance_matrix)
print( min_distances)
print(indices)

[[22 34]
 [20 69]
 [57 16]
 [ 5 74]
 [24 81]]
[[86 17]
 [20  9]
 [86 31]
 [12 44]
 [ 0 85]
 [48  6]
 [30 28]
 [35 89]]
[[66.21933252 25.07987241 64.07027392 14.14213562 55.54277631 38.20994635
  10.         56.5154846 ]
 [84.02380615 60.         76.15773106 26.2488095  25.61249695 68.94200461
  42.20189569 25.        ]
 [29.01723626 37.65634077 32.64965543 53.         89.49860334 13.45362405
  29.54657341 76.24303247]
 [99.04544412 66.70832032 91.70605214 30.8058436  12.08304597 80.45495634
  52.35456045 33.54101966]
 [89.10667764 72.11102551 79.64923101 38.89730068 24.33105012 78.74642849
  53.33854141 13.60147051]]
[10.         25.         13.45362405 12.08304597 13.60147051]
[3 4 5 6 7]
